workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

image: docker:git
services:
  - docker:dind
before_script:
  - apk add --update bash coreutils tar curl git
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci .industrial_ci -b master

variables:
  DOCKER_TLS_CERTDIR: ""
  BEFORE_INIT: "sh -c 'echo \"deb [arch=amd64] http://ftp-osl.osuosl.org/pub/ros2 focal main\" ' > /etc/apt/sources.list.d/ros2-latest.list"
  DOCKER_IMAGE: "cardboardcode/epd-foxy-base:latest"
  PARALLEL_TESTS: "true"  # Global Variable

foxy-main:
  script: .industrial_ci/gitlab.sh ROS_DISTRO=foxy ROS_REPO=main

foxy-testing:
  script: .industrial_ci/gitlab.sh ROS_DISTRO=foxy ROS_REPO=testing
